CREATE TABLE IF NOT EXISTS think (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    points INT NOT NULL,
    image LONGTEXT,
    colorBackground VARCHAR(7) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);